export const categories = [
  {
    id: 'fantasy',
    name: 'Fantasy/Magical',
    modifiers: [
      'magical forest',
      'enchanted castle',
      'mystical creatures',
      'dragon lair',
      'wizard tower',
      'fairy garden',
    ],
    styles: [
      'ethereal lighting',
      'magical atmosphere',
      'fantasy art style',
      'dreamlike quality',
      'mystical glow',
    ],
  },
  {
    id: 'realistic',
    name: 'Realistic',
    modifiers: [
      'natural landscape',
      'urban scene',
      'portrait',
      'still life',
      'architecture',
    ],
    styles: [
      'photorealistic',
      'cinematic lighting',
      'golden hour',
      'studio lighting',
      'documentary style',
    ],
  },
  {
    id: 'anime',
    name: 'Anime/Manga',
    modifiers: [
      'anime character',
      'manga scene',
      'chibi style',
      'action pose',
      'emotional moment',
    ],
    styles: [
      'anime art style',
      'cel shaded',
      'vibrant colors',
      'detailed linework',
      'dynamic composition',
    ],
  },
  {
    id: 'abstract',
    name: 'Abstract',
    modifiers: [
      'geometric shapes',
      'fluid forms',
      'color explosion',
      'fractal patterns',
      'minimalist design',
    ],
    styles: [
      'abstract art',
      'modern art style',
      'experimental technique',
      'mixed media',
      'contemporary art',
    ],
  },
  {
    id: 'scifi',
    name: 'Sci-fi',
    modifiers: [
      'futuristic city',
      'space station',
      'alien landscape',
      'cyberpunk street',
      'robot design',
    ],
    styles: [
      'science fiction art',
      'neon lighting',
      'holographic effect',
      'technological aesthetic',
      'futuristic design',
    ],
  },
  {
    id: 'nature',
    name: 'Nature',
    modifiers: [
      'mountain range',
      'tropical beach',
      'dense forest',
      'desert landscape',
      'underwater scene',
    ],
    styles: [
      'nature photography',
      'landscape art',
      'environmental art',
      'botanical illustration',
      'wildlife art',
    ],
  },
];